[book]
authors = ["Roker2","CakesTwix","Ultra119","SanyaPilot"]
language = "ru"
multilingual = true
src = "src"
title = "About Android Building"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/Roker2/BookAboutBuilding"
additional-css = ["./theme/css/language-picker.css"]

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false

[output.epub]
optional = true

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]
