[book]
authors = ["Roker2","CakesTwix","Ultra119","SanyaPilot"]
language = "ru"
multilingual = false
src = "src"
title = "About Android Building"

[output.html]
git-repository-url = "https://github.com/Roker2/BookAboutBuilding"

[output.epub]
optional = true
